### PR TITLE
- fixes a bug where non-flagabble enum properties would not be generated with proper type in java

### LINKED ISSUE #352: java: affecting values with enums should be using enumsets for flaggable properties
Whenever a property can contain a collection of enum values (equivalent of flaggable from dotnet in java), the snippet should be using an enumset to affect the value. https://docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&tabs=java

### PR DESCRIPTION
**Pull request by baywet**
fixes #352

https://github.com/microsoftgraph/microsoft-graph-docs/compare/snippet-generation/31225...snippet-generation/31231?expand=1

### CODE REVIEW

File: CodeSnippetsReflection/LanguageGenerators/JavaGenerator.cs [hunk 1]
```diff
@@ -257,14 +257,23 @@ private string JavaGenerateObjectFromJson(ODataPathSegment pathSegment, string j
...
+                            foreach (var element in array)
+                            {
+                                var enumString = GenerateEnumString(element.Value<string>(), pathSegment, path);
+                                stringBuilder.Append($"{currentListName}.add({enumString});\r\n");
+                            }
                         }
                         else
                         {
-                            stringBuilder.Append($"LinkedList<String> {path.Last()}List = new LinkedList<String>();\r\n");
+                            stringBuilder.Append($"LinkedList<String> {currentListName} = new LinkedList<String>();\r\n");
```
Comment (MIchaelMainer) [inline CodeSnippetsReflection/LanguageGenerators/JavaGenerator.cs:272]: I suggest that we either:
1) Make this an `elseif` that checks that this is an array of strings with a subsequent `else` that reports the identification that this as a new scenario that we need to support. For example, if we get an array of any OData primitive types that is not a string, we should identify the scenario and where we need to add the change. 
2) Add conditions for all OData primitive types.

I prefer the first for now.

Can we check that this is an array of strings?

**Review by MIchaelMainer — CHANGES_REQUESTED** [review]

File: CodeSnippetsReflection/LanguageGenerators/JavaGenerator.cs (hunk 1 above)
Comment (baywet) [reply CodeSnippetsReflection/LanguageGenerators/JavaGenerator.cs]: great minds connect! (did I properly translate the expression?) I was hunting for those kind of issues (wrong mapping of collections) and I was thinking about tackling the issue in a separate PR. But I included the fix here as well.

**Review by zengin — DISMISSED** [review]

**Review by zengin — APPROVED** [review]

**Review by nikithauc — APPROVED** [review]

**Review by MIchaelMainer — APPROVED** [review]
