### PR TITLE
Fix sending PATCH requests with a full request body as the stream

### LINKED ISSUE #288: OneNote Page Update snippet is wrong
C# types are not compatible with the page update request.

Docs:
https://docs.microsoft.com/en-us/graph/api/page-update?view=graph-rest-1.0&tabs=http#request

HTTP Snippet:
```http
PATCH https://graph.microsoft.com/v1.0/me/onenote/pages/{id}/content
Content-type: application/json
Content-length: 312

[
   {
    'target':'#para-id',
    'action':'insert',
    'position':'before',
    'content':'<img src="image-url-or-part-name" alt="image-alt-text" />'
  }, 
  {
    'target':'#list-id',
    'action':'append',
    'content':'<li>new-page-content</li>'
  }
]
```

C# snippet:
```csharp
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var stream = new List<Stream>()
{
	new Stream
	{
		Target = "#para-id",
		Action = "insert",
		Position = "before",
		Content = "<img src=\"image-url-or-part-name\" alt=\"image-alt-text\" />"
	},
	new Stream
	{
		Target = "#list-id",
		Action = "append",
		Content = "<li>new-page-content</li>"
	}
};

var pages = new OnenotePage();
pages.Content = content;

await graphClient.Me.Onenote.Pages["{id}"].Content
	.Request()
	.UpdateAsync(pages);
``` 
[AB#6988](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6988)

### PR DESCRIPTION
**Pull request by zengin**
[Snippets diff](https://github.com/microsoftgraph/microsoft-graph-docs/compare/snippet-generation/38469...snippet-generation/38470?expand=1)

Fixes 1 C# Beta and 1 C# V1 compilation tests in Raptor.

Fixes #288

### CODE REVIEW

File: CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs [hunk 1]
```diff
@@ -323,6 +323,12 @@ private static string CSharpGenerateResourcesPath(SnippetModel snippetModel)
         /// <param name="path">List of strings/identifier showing the path through the Edm/json structure to reach the Class Identifier from the segment</param>
         private string CSharpGenerateObjectFromJson(ODataPathSegment pathSegment, string jsonBody , ICollection<string> path)
         {
+            if (pathSegment.EdmType.FullTypeName() == "Edm.Stream")
```
Comment (andrueastman) [inline CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs:326]: It seems there is a broken test because of this line. In the event that the `pathSegment` is an `OperationSegment` the edmType could be null.

File: CodeSnippetsReflection.Test/CSharpGeneratorShould.cs [hunk 2]
```diff
@@ -172,6 +172,45 @@ public void TypeIsInferredFromActionParametersForNullableType()
             Assert.Contains("String physicalDeviceId = null;", result);
         }
 
+        [Fact]
```
Comment (andrueastman) [inline CodeSnippetsReflection.Test/CSharpGeneratorShould.cs:175]: 👍

File: CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs (hunk 1 above)
Comment (zengin) [reply CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs]: Thanks for the analysis of the test failure. I should have been more careful about defensive programming ;)

**Review by andrueastman — APPROVED** [review]
