### PR TITLE
- fixes java generation for Guid, DateTimeOffset, Double, and Binary types

### LINKED ISSUE #341: An Incompatible types error is reported in the sample code.
An Incompatible types error is reported in the sample code.
How to use the ConversationMemberCollectionPage ?
`channel.members = membersList;`
Required: com.microsoft.graph.requests.extensions.ConversationMemberCollectionPage
Found: java.util.LinkedList

https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=java

```
IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

Channel channel = new Channel();
channel.membershipType = ChannelMembershipType.PRIVATE;
channel.displayName = "My First Private Channel";
channel.description = "This is my first private channels";
LinkedList<ConversationMember> membersList = new LinkedList<ConversationMember>();
AadUserConversationMember members = new AadUserConversationMember();
members.additionalDataManager().put("user@odata.bind", new JsonPrimitive("https://graph.microsoft.com/v1.0/users('{user_id}')"));
LinkedList<String> rolesList = new LinkedList<String>();
rolesList.add("owner");
members.roles = rolesList;
membersList.add(members);
channel.members = membersList;

graphClient.teams("{group_id}").channels()
	.buildRequest()
	.post(channel);
```

### LINKED ISSUE #350: Java datetime snippets should be using the calendar object
Because the snippet is not trying to parse the string value and affects it directly to the Calendar property it fails to compile.
https://docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=java

### LINKED ISSUE #351: java with references collection pages should be used instead of regular collection pages when necessary
A lot of identity collection navigation properties return types with references, which impacts the interface to use for the collection page and causes compilation to fail.
https://docs.microsoft.com/en-us/graph/api/educationuser-list-schools?view=graph-rest-1.0&tabs=java

### LINKED ISSUE #353: java: number values should use the property type when affected
When we affect a number value to a property today, we simply put the literal. This doesn't work for properties of type double/long etc... which need to be suffixed to be recognized as something else than an int (with D, L etc...)
https://docs.microsoft.com/en-us/graph/api/worksheet-post-charts?view=graph-rest-1.0&tabs=java

### LINKED ISSUE #354: java: binary types need to be converted before affectation
Whenever we affect a property of type byte[], the value from the http snippet is usually the base64 encoded string. It needs to be decoded before we affect it to the property so the snippet can build.
https://docs.microsoft.com/en-us/graph/api/event-post-attachments?view=graph-rest-1.0&tabs=java

### LINKED ISSUE #355: java: methods collection pages need to use the specialized interface instead of the default one
IDriveItemGetActivitiesByIntervalCollectionPage  instead of IItemActivityStatCollectionPage for https://docs.microsoft.com/en-us/graph/api/itemactivitystat-getactivitybyinterval?view=graph-rest-1.0&tabs=java

### LINKED ISSUE #357: java: edm Json should map to JsonElement
https://docs.microsoft.com/en-us/graph/api/filter-apply?view=graph-rest-1.0&tabs=java

### LINKED ISSUE #359: java: guid properties should be parsed before being assigned
https://docs.microsoft.com/en-us/graph/api/user-post-approleassignments?view=graph-rest-1.0&tabs=java

### LINKED ISSUE #360: java: json payload quotes are not being escaped
https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=java

### PR DESCRIPTION
**Pull request by baywet**
fixes #353
fixes #350
fixes #354
fixes #359
fixes #357
fixes #360
fixes #351
fixes #355
fixes #341

for information the generation updates are here, it contains other changes however.
https://github.com/microsoftgraph/microsoft-graph-docs/compare/snippet-generation/30952...snippet-generation/30968?expand=1

### CODE REVIEW

**Comment by baywet** [comment]
for information the generation updates are here, it contains other changes however.
https://github.com/microsoftgraph/microsoft-graph-docs/pull/new/snippet-generation/30820

**Comment by zengin** [comment]
Started a new build on:
- microsoft-graph-docs: a new branch (zengin/prBase) off of snippet-generation/30917 (today's generation). Purpose of new branch is to make sure that [PR merge](https://github.com/microsoftgraph/microsoft-graph-docs/pull/10514/files) doesn't delete our base branch.
- microsoft-graph-explorer-api: bugfix/java-guid-parse

The diff between the new snippet-generation branch and zengin/prBase should give us only the changes in your branch and the changes in dev that haven't made into master.
https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=30949&view=results

If you want to remove changes in dev from your diff, you can also do this in two steps:
1. Generate from dev
2. Generate from your branch setting the base branch from step 1.

That should help us highlight only the new changes.

**Comment by baywet** [comment]
To recap the teams conversation:
1. kick off the snippet generation pipeline from the dev branch
2. kick off the snippet generation pipeline from this branch for the main repo, and from the branch generated by step1 for the docs repo (resources menu)
3. post the diff here

File: CodeSnippetsReflection/LanguageGenerators/JavaGenerator.cs [hunk 1]
```diff
@@ -271,6 +290,70 @@ private string JavaGenerateObjectFromJson(ODataPathSegment pathSegment, string j
...
+                    case "Double":
+                        return $"{stringParameter}d";
+
+                    case "Int64":
+                        return $"{stringParameter}L";
+
+                    case "TimeOfDay":
+                        return DateTime.TryParse(stringParameter, out var timeOfDay)
+                            ? $"new TimeOfDay({timeOfDay.Hour}, {timeOfDay.Minute}, {timeOfDay.Second})"
+                            : "new TimeOfDay(0, 0, 0)";
```
Comment (zengin) [inline CodeSnippetsReflection/LanguageGenerators/JavaGenerator.cs:334]: Some context around this code:
If you took this one from the C# generator, there was an issue where running this in the pipeline vs running it locally were generating different results (one is UTC, the other is local time), which generates diffs in local compares.

That said, hopefully we won't need to run generation locally anymore as the pipeline now allows arbitrary branches and it will always be UTC.

**Review by zengin — APPROVED** [review]
🚀 LGTM.

**Review by andrueastman — APPROVED** [review]
👍 On adding the tests

File: CodeSnippetsReflection/LanguageGenerators/JavaGenerator.cs (hunk 1 above)
Comment (baywet) [reply CodeSnippetsReflection/LanguageGenerators/JavaGenerator.cs:334]: I did take it from the C# generator but I'm not facing the issue.
This is mainly because the unit tests I added are designed in such a way that they test the aspect they are responsible for and not the whole text value. (one of the key takeaways I remember from reading Aspect Oriented Programming years ago :) )
So in this case, as you can see [here](https://github.com/microsoftgraph/microsoft-graph-explorer-api/pull/363/files#diff-0af677c1349ad3cae6c6995f8957cddd73e82fab22626a4018ca05349392c4a9R318) my test is only testing for the presence of TimeOfDay, not for the values themselves.

Comment (zengin) [reply CodeSnippetsReflection/LanguageGenerators/JavaGenerator.cs:334]: This was more on the diffs that I used to create locally for code review. When I did a full run locally, it was generating values for actual snippets different than what is in the docs repo, which was polluting the diff. This is pretty much no longer an issue due to the ease of generation using the pipeline now using arbitrary branches.

Regarding the unit tests, thanks for bringing in your AOP wisdom into the codebase 👍
