### PR TITLE
Fixes fetching localized sample queries

### LINKED ISSUE #237: Localized samples are not showing on Graph Explorer
Attempting to fetch localized sample queries returns an error " "Error setting value to 'Category' on 'GraphExplorerSamplesService.Models.SampleQueryModel'."

### PR DESCRIPTION
**Pull request by irvinesunday**
Closes #237

Proposes:
- Fixing the issue of displaying localized sample queries by:
  - Removing the validation of setting Properties: `Category` and `HumanName` and their corresponding tests.
- Ordering the sample queries alphabetically starting with "Getting Started" for en-US preferred language. There is still no defined way of ordering the localized sample queries by their Category.

### CODE REVIEW

**Comment by darrelmiller** [comment]
We should come back to this after Build and use the english file as a the primary sample content and only use the localized files for translating the descriptive properties.

File: GraphWebApi/Controllers/GraphExplorerSamplesController.cs [hunk 1]
```diff
@@ -334,13 +334,22 @@ private async Task<SampleQueriesList> FetchSampleQueriesListAsync(string localeC
...
                  * objects that will be used to add new sample queries*/
                 return new SampleQueriesList();
             }
 
+            bool orderSamples = false;
+
+            if (localeCode.Equals("en-us", StringComparison.OrdinalIgnoreCase))
+            {
+                // Current business process only supports ordering of the English
+                // version of the sample queries.
```
Comment (ddyett) [inline GraphWebApi/Controllers/GraphExplorerSamplesController.cs:347]: Do we have a bug or issue tracking this? Good to reference here.

Comment (irvinesunday) [reply GraphWebApi/Controllers/GraphExplorerSamplesController.cs:347]: GitHub: https://github.com/microsoftgraph/microsoft-graph-explorer-api/issues/241
AB: https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_workitems/edit/4690
